services:
  api-mesafacil:
    build: .
    image: mesafacil:1.0
    ports:
      - "8080:8080"
    networks:
      - api-network
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mesafacil?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    restart: on-failure

  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    ports:
      - "3306:3306"
    networks:
      - api-network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mesafacil
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  api-network:
    driver: bridge

volumes:
  mysql-data: